name: rtorrent

services:
  rtorrent:
    build:
      context: ../..
      args:
        LIBTORRENT_VERSION: ${LIBTORRENT_VERSION:-0.16.7}
        RTORRENT_VERSION: ${RTORRENT_VERSION:-0.16.7}
    image: docker-rtorrent:${RTORRENT_VERSION:-0.16.7}
    container_name: rtorrent
    networks:
      - rtorrent
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${RT_INC_PORT}"
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    env_file:
      - "rtorrent.env"
    volumes:
      - "./data:/data"
      - "./downloads:/downloads"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always

  rtorrent-logs:
    image: bash
    container_name: rtorrent-logs
    command: bash -c 'tail -f /log/*.log'
    network_mode: none
    depends_on:
      - rtorrent
    volumes:
      - "./data/rtorrent/log:/log"
    restart: always

networks:
  rtorrent:
    name: rtorrent
