name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  schedule:
    - cron: '0 8 */6 * *'
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    uses: docker/github-builder/.github/workflows/bake.yml@70313223e2665c3211b454b3fea6534624e78d64 # v1.4.0
    permissions:
      contents: read # same as global permissions
      id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write # required to push to GHCR
    with:
      setup-qemu: true
      target: image-all
      cache: true
      cache-scope: build
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      set-meta-labels: true
      meta-images: |
        ghcr.io/${{ github.repository_owner }}/docker-rtorrent
      meta-tags: |
        type=ref,event=tag
        type=ref,event=pr
        type=edge
      meta-labels: |
        org.opencontainers.image.title=docker-rtorrent
        org.opencontainers.image.description=rTorrent Docker image
        org.opencontainers.image.vendor=${{ github.repository_owner }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
